//user reducer types
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER' 
export const SET_OTHER_USER = 'SET_OTHER_USER' 
export const LOADING_USER = 'LOADING_USER' 
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED' 
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED' 
export const SET_SPECIFIC_QUESTION = 'SET_SPECIFIC_QUESTION' 
export const SET_SPECIFIC_ANSWERS = 'SET_SPECIFIC_ANSWERS' 
export const SET_ALL_USER = 'SET_ALL_USER' 
export const EDIT_USER_DETAILS = 'EDIT_USER_DETAILS' 

//ui reducer types
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS' 
export const MARK_ALL_READ = 'MARK_ALL_READ' 

//data reducer types
export const SET_QUESTIONS = 'SET_QUESTIONS'
export const SET_ANSWERS = 'SET_ANSWERS'
export const LOADING_DATA = 'LOADING_DATA'
export const LIKE_QUESTION = 'LIKE_QUESTION'
export const DISLIKE_QUESTION = 'DISLIKE_QUESTION'
export const POST_QUESTION = 'POST_QUESTION'
export const POST_ANSWER = 'POST_ANSWER'
export const DELETE_ANSWER = 'DELETE_ANSWER'
export const DELETE_QUESTION = 'DELETE_QUESTION'
export const TOGGLE_CORRECT_STATUS = 'TOGGLE_CORRECT_STATUS'
