//user reducer types
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER' 
export const LOADING_USER = 'LOADING_USER' 
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED' 
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED' 
export const SET_SPECIFIC_QUESTION = 'SET_SPECIFIC_QUESTION' 
export const SET_SPECIFIC_ANSWERS = 'SET_SPECIFIC_ANSWERS' 

//ui reducer types

//data reducer types
export const SET_QUESTIONS = 'SET_QUESTIONS'
export const SET_ANSWERS = 'SET_ANSWERS'
export const LOADING_DATA = 'LOADING_DATA'
export const LIKE_QUESTION = 'LIKE_QUESTION'
export const DISLIKE_QUESTION = 'DISLIKE_QUESTION'
